# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @minimal-tmux-bg "#ff5539"

# toggle the status bar
bind-key b set-option status

# https://github.com/vimpostor/vim-tpipeline?tab=readme-ov-file#installation
set -g focus-events on
set -g status-style bg=default
set -g status-left-length 90
set -g status-right-length 90
set -g status-justify absolute-centre

# Ctrl+b, r to reload the config
bind r source-file ~/.config/tmux/tmux.conf

run '~/.tmux/plugins/tpm/tpm'
