stages:
  - lint

default:
  image: alpine

.standard-rules:       # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lint-salt:
  stage: lint
  script:
    - ci/salt-lint.sh
