on:
  - push

defaults:
  run:
    shell: "sh -e {0}"

jobs:
  test:
    runs-on: codeberg-tiny
    container: alpine:latest
    name: Salt Lint
    steps:
      - uses: actions/checkout@v4

      - name: Run salt-lint
        run: scripts/salt-lint.sh
