on:
  - push

defaults:
  run:
    shell: "sh -e {0}"

jobs:
  test:
    runs-on: codeberg-tiny
    container: alpine:latest
    name: Salt Lint
    steps:
      - run: |
            set -xeu
            apk update
            apk add git
            git clone "${GITHUB_SERVER}/${GITHUB_REPOSITORY}" .

      - name: Run salt-lint
        run: scripts/salt-lint.sh
