---@type LazySpec
return {

  "AstroNvim/astrocommunity",

  -- { import = "astrocommunity.ai.kurama622-llm-nvim" },

  { import = "astrocommunity.bars-and-lines.dropbar-nvim" },
  -- { import = "astrocommunity.bars-and-lines.feline-nvim" },
  -- { import = "astrocommunity.bars-and-lines.lualine-nvim" },
  -- { import = "astrocommunity.bars-and-lines.scope-nvim" },
  { import = "astrocommunity.bars-and-lines.smartcolumn-nvim" },
  { import = "astrocommunity.bars-and-lines.statuscol-nvim" },
  -- { import = "astrocommunity.bars-and-lines.vim-illuminate" },

  -- { import = "astrocommunity.code-runner.compiler-nvim" },
  -- { import = "astrocommunity.code-runner.conjure" },
  -- { import = "astrocommunity.code-runner.executor-nvim" },
  -- { import = "astrocommunity.code-runner.mf-runner-nvim" },
  -- { import = "astrocommunity.code-runner.molten-nvim" },
  -- { import = "astrocommunity.code-runner.overseer-nvim" },
  -- { import = "astrocommunity.code-runner.sniprun" },
  -- { import = "astrocommunity.code-runner.toggletasks-nvim" },
  -- { import = "astrocommunity.code-runner.vim-slime" },

  -- { import = "astrocommunity.color.ccc-nvim" },
  -- { import = "astrocommunity.color.headlines-nvim"},
  { import = "astrocommunity.color.huez-nvim" },
  -- { import = "astrocommunity.color.mini-hipatterns" },
  { import = "astrocommunity.color.modes-nvim" },
  -- { import = "astrocommunity.color.nvim-highlight-colors" },
  -- { import = "astrocommunity.color.tint-nvim" },
  { import = "astrocommunity.color.transparent-nvim" },
  { import = "astrocommunity.color.twilight-nvim" },
  -- { import = "astrocommunity.color.vim-highlighter" },

  { import = "astrocommunity.colorscheme.aurora" },
  { import = "astrocommunity.colorscheme.bamboo-nvim" },
  { import = "astrocommunity.colorscheme.bluloco-nvim" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.colorscheme.citruszest-nvim" },
  { import = "astrocommunity.colorscheme.cyberdream-nvim" },
  { import = "astrocommunity.colorscheme.dracula-nvim" },
  { import = "astrocommunity.colorscheme.eldritch-nvim" },
  { import = "astrocommunity.colorscheme.everblush-nvim" },
  { import = "astrocommunity.colorscheme.everforest" },
  { import = "astrocommunity.colorscheme.fluoromachine-nvim" },
  { import = "astrocommunity.colorscheme.github-nvim-theme" },
  { import = "astrocommunity.colorscheme.gruvbox-baby" },
  { import = "astrocommunity.colorscheme.gruvbox-nvim" },
  { import = "astrocommunity.colorscheme.helix-nvim" },
  { import = "astrocommunity.colorscheme.horizon-nvim" },
  { import = "astrocommunity.colorscheme.hybrid-nvim" },
  { import = "astrocommunity.colorscheme.iceberg-vim" },
  { import = "astrocommunity.colorscheme.kanagawa-nvim" },
  { import = "astrocommunity.colorscheme.kanagawa-paper-nvim" },
  { import = "astrocommunity.colorscheme.lackluster-nvim" },
  { import = "astrocommunity.colorscheme.melange-nvim" },
  { import = "astrocommunity.colorscheme.mellifluous-nvim" },
  { import = "astrocommunity.colorscheme.mellow-nvim" },
  { import = "astrocommunity.colorscheme.miasma-nvim" },
  { import = "astrocommunity.colorscheme.mini-base16" },
  { import = "astrocommunity.colorscheme.modus-nvim" },
  { import = "astrocommunity.colorscheme.monokai-pro-nvim" },
  { import = "astrocommunity.colorscheme.neofusion-nvim" },
  { import = "astrocommunity.colorscheme.neosolarized-nvim" },
  { import = "astrocommunity.colorscheme.night-owl-nvim" },
  { import = "astrocommunity.colorscheme.nightfox-nvim" },
  { import = "astrocommunity.colorscheme.nord-nvim" },
  { import = "astrocommunity.colorscheme.nordic-nvim" },
  { import = "astrocommunity.colorscheme.nvim-juliana" },
  { import = "astrocommunity.colorscheme.oldworld-nvim" },
  { import = "astrocommunity.colorscheme.onedarkpro-nvim" },
  { import = "astrocommunity.colorscheme.oxocarbon-nvim" },
  { import = "astrocommunity.colorscheme.palenight-nvim" },
  { import = "astrocommunity.colorscheme.poimandres-nvim" },
  { import = "astrocommunity.colorscheme.rose-pine" },
  { import = "astrocommunity.colorscheme.solarized-osaka-nvim" },
  { import = "astrocommunity.colorscheme.sonokai" },
  { import = "astrocommunity.colorscheme.tokyodark-nvim" },
  { import = "astrocommunity.colorscheme.tokyonight-nvim" },
  { import = "astrocommunity.colorscheme.vim-dogrun" },
  { import = "astrocommunity.colorscheme.vim-moonfly-colors" },
  { import = "astrocommunity.colorscheme.vim-nightfly-colors" },
  { import = "astrocommunity.colorscheme.vscode-nvim" },

  -- { import = "astrocommunity.comment.mini-comment" },
  -- { import = "astrocommunity.comment.ts-comments-nvim" },

  -- { import = "astrocommunity.completion.avante-nvim" },
  -- { import = "astrocommunity.completion.blink-cmp" },
  -- { import = "astrocommunity.completion.blink-cmp-emoji" },
  -- { import = "astrocommunity.completion.blink-cmp-git" },
  -- { import = "astrocommunity.completion.blink-cmp-tmux" },
  -- { import = "astrocommunity.completion.cmp-calc" },
  -- { import = "astrocommunity.completion.cmp-cmdline" },
  -- { import = "astrocommunity.completion.cmp-emoji" },
  -- { import = "astrocommunity.completion.cmp-git" },
  -- { import = "astrocommunity.completion.cmp-latex-symbols" },
  -- { import = "astrocommunity.completion.cmp-nerdfont" },
  -- { import = "astrocommunity.completion.cmp-nvim-lua" },
  -- { import = "astrocommunity.completion.cmp-spell" },
  -- { import = "astrocommunity.completion.cmp-tmux" },
  -- { import = "astrocommunity.completion.cmp-under-comparator" },
  -- { import = "astrocommunity.completion.codeium-nvim" },
  -- { import = "astrocommunity.completion.codeium-vim" },
  -- { import = "astrocommunity.completion.copilot-cmp" },
  -- { import = "astrocommunity.completion.copilot-lua" },
  -- { import = "astrocommunity.completion.copilot-lua-cmp" },
  -- { import = "astrocommunity.completion.copilot-vim" },
  -- { import = "astrocommunity.completion.copilot-vim-cmp" },
  -- { import = "astrocommunity.completion.coq_nvim" },
  -- { import = "astrocommunity.completion.fittencode-nvim" },
  -- { import = "astrocommunity.completion.magazine-nvim" },
  -- { import = "astrocommunity.completion.mini-completion" },
  -- { import = "astrocommunity.completion.nvim-cmp" },
  -- { import = "astrocommunity.completion.nvim-cmp-buffer-lines" },
  -- { import = "astrocommunity.completion.supermaven-nvim" },
  -- { import = "astrocommunity.completion.tabby-nvim" },
  -- { import = "astrocommunity.completion.tabnine-nvim" },

  -- { import = "astrocommunity.debugging.nvim-bqf" },
  -- { import = "astrocommunity.debugging.nvim-chainsaw" },
  -- { import = "astrocommunity.debugging.nvim-dap-repl-highlights" },
  -- { import = "astrocommunity.debugging.nvim-dap-view" },
  -- { import = "astrocommunity.debugging.nvim-dap-virtual-text" },
  -- { import = "astrocommunity.debugging.persistent-breakpoints-nvim" },
  { import = "astrocommunity.debugging.telescope-dap-nvim" },

  { import = "astrocommunity.diagnostics.error-lens-nvim" },
  -- { import = "astrocommunity.diagnostics.lsp_lines-nvim" },
  { import = "astrocommunity.diagnostics.tiny-inline-diagnostic-nvim" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },

  -- { import = "astrocommunity.docker.lazydocker" },

  -- { import = "astrocommunity.editing-support.auto-save-nvim" },
  -- { import = "astrocommunity.editing-support.bigfile-nvim" },
  -- { import = "astrocommunity.editing-support.chatgpt-nvim" },
  -- { import = "astrocommunity.editing-support.cloak-nvim" },
  -- { import = "astrocommunity.editing-support.comment-box-nvim" },
  -- { import = "astrocommunity.editing-support.conform-nvim" },
  -- { import = "astrocommunity.editing-support.copilotchat-nvim" },
  -- { import = "astrocommunity.editing-support.cutlass-nvim" },
  -- { import = "astrocommunity.editing-support.dial-nvim" },
  -- { import = "astrocommunity.editing-support.hypersonic-nvim" },
  -- { import = "astrocommunity.editing-support.mcphub-nvim" },
  -- { import = "astrocommunity.editing-support.mini-operators" },
  -- { import = "astrocommunity.editing-support.mini-splitjoin" },
  -- { import = "astrocommunity.editing-support.multicursors-nvim" },
  -- { import = "astrocommunity.editing-support.multiple-cursors-nvim" },
  { import = "astrocommunity.editing-support.neogen" },
  { import = "astrocommunity.editing-support.nvim-context-vt" },
  { import = "astrocommunity.editing-support.nvim-devdocs" },
  -- { import = "astrocommunity.editing-support.nvim-origami" },
  -- { import = "astrocommunity.editing-support.nvim-parinfer" },
  -- { import = "astrocommunity.editing-support.nvim-regexplainer" },
  { import = "astrocommunity.editing-support.nvim-treesitter-context" },
  -- { import = "astrocommunity.editing-support.nvim-treesitter-endwise" },
  -- { import = "astrocommunity.editing-support.nvim-treesitter-sexp" },
  -- { import = "astrocommunity.editing-support.nvim-ts-rainbow" },
  -- { import = "astrocommunity.editing-support.nvim-ts-rainbow2" },
  -- { import = "astrocommunity.editing-support.quick-scope" },
  -- { import = "astrocommunity.editing-support.rainbow-delimiters-nvim" },
  -- { import = "astrocommunity.editing-support.refactoring-nvim" },
  -- { import = "astrocommunity.editing-support.stickybuf-nvim" },
  -- { import = "astrocommunity.editing-support.suda-vim" },
  -- { import = "astrocommunity.editing-support.telescope-undo-nvim" },
  -- { import = "astrocommunity.editing-support.text-case-nvim" },
  { import = "astrocommunity.editing-support.todo-comments-nvim" },
  -- { import = "astrocommunity.editing-support.treesj" },
  -- { import = "astrocommunity.editing-support.true-zen-nvim" },
  -- { import = "astrocommunity.editing-support.ultimate-autopair-nvim" },
  -- { import = "astrocommunity.editing-support.undotree" },
  -- { import = "astrocommunity.editing-support.vim-doge" },
  -- { import = "astrocommunity.editing-support.vim-exchange" },
  -- { import = "astrocommunity.editing-support.vim-move" },
  -- { import = "astrocommunity.editing-support.vim-visual-multi" },
  -- { import = "astrocommunity.editing-support.wildfire-nvim" },
  -- { import = "astrocommunity.editing-support.yanky-nvim" },
  -- { import = "astrocommunity.editing-support.zen-mode-nvim" },

  -- { import = "astrocommunity.file-explorer.mini-files" },
  -- { import = "astrocommunity.file-explorer.oil-nvim" },
  -- { import = "astrocommunity.file-explorer.telescope-file-browser-nvim" },

  -- { import = "astrocommunity.fuzzy-finder.fzf-lua" },
  -- { import = "astrocommunity.fuzzy-finder.namu-nvim" },
  -- { import = "astrocommunity.fuzzy-finder.snacks-picker" },
  -- { import = "astrocommunity.fuzzy-finder.telescope-nvim" },
  -- { import = "astrocommunity.fuzzy-finder.telescope-zoxide" },

  -- { import = "astrocommunity.game.leetcode-nvim" },

  -- { import = "astrocommunity.git.blame-nvim" },
  -- { import = "astrocommunity.git.diffview-nvim" },
  -- { import = "astrocommunity.git.fugit2-nvim" },
  -- { import = "astrocommunity.git.gist-nvim" },
  -- { import = "astrocommunity.git.git-blame-nvim" },
  -- { import = "astrocommunity.git.gitgraph-nvim" },
  -- { import = "astrocommunity.git.gitlinker-nvim" },
  -- { import = "astrocommunity.git.mini-diff" },
  -- { import = "astrocommunity.git.mini-git" },
  -- { import = "astrocommunity.git.neogit" },
  -- { import = "astrocommunity.git.nvim-tinygit" },
  -- { import = "astrocommunity.git.octo-nvim" },
  -- { import = "astrocommunity.git.openingh-nvim" },

  -- { import = "astrocommunity.icon.mini-icons" },

  -- { import = "astrocommunity.indent.indent-blankline-nvim" },
  -- { import = "astrocommunity.indent.indent-rainbowline" },
  -- { import = "astrocommunity.indent.indent-tools-nvim" },
  -- { import = "astrocommunity.indent.mini-indentscope" },
  { import = "astrocommunity.indent.snacks-indent-hlchunk" },

  -- { import = "astrocommunity.keybinding.hydra-nvim" },
  -- { import = "astrocommunity.keybinding.mini-clue" },
  -- { import = "astrocommunity.keybinding.nvcheatsheet-nvim" },

  -- { import = "astrocommunity.lsp.actions-preview-nvim" },
  -- { import = "astrocommunity.lsp.coc-nvim" },
  -- { import = "astrocommunity.lsp.delimited-nvim" },
  { import = "astrocommunity.lsp.garbage-day-nvim" },
  -- { import = "astrocommunity.lsp.inc-rename-nvim" },
  -- { import = "astrocommunity.lsp.lsp-inlayhints-nvim" },
  -- { import = "astrocommunity.lsp.lsp-lens-nvim" },
  -- { import = "astrocommunity.lsp.lsp-signature-nvim" },
  -- { import = "astrocommunity.lsp.lsplinks-nvim" },
  -- { import = "astrocommunity.lsp.lspsaga-nvim" },
  -- { import = "astrocommunity.lsp.nvim-java" },
  -- { import = "astrocommunity.lsp.nvim-lint" },
  -- { import = "astrocommunity.lsp.nvim-lsp-endhints" },
  -- { import = "astrocommunity.lsp.nvim-lsp-file-operations" },
  -- { import = "astrocommunity.lsp.ts-error-translator-nvim" },

  -- { import = "astrocommunity.markdown-and-latex.glow-nvim" },
  -- { import = "astrocommunity.markdown-and-latex.markdown-preview-nvim" },
  -- { import = "astrocommunity.markdown-and-latex.markmap-nvim" },
  -- { import = "astrocommunity.markdown-and-latex.markview-nvim" },
  -- { import = "astrocommunity.markdown-and-latex.peek-nvim" },
  -- { import = "astrocommunity.markdown-and-latex.render-markdown-nvim" },
  -- { import = "astrocommunity.markdown-and-latex.vimtex" },

  -- { import = "astrocommunity.media.codesnap-nvim" },
  -- { import = "astrocommunity.media.cord-nvim" },
  -- { import = "astrocommunity.media.drop-nvim" },
  -- { import = "astrocommunity.media.image-nvim" },
  -- { import = "astrocommunity.media.img-clip-nvim" },
  -- { import = "astrocommunity.media.neocord-nvim" },
  -- { import = "astrocommunity.media.pets-nvim" },
  -- { import = "astrocommunity.media.presence-nvim" },
  -- { import = "astrocommunity.media.vim-wakatime" },

  -- { import = "astrocommunity.motion.before-nvim" },
  -- { import = "astrocommunity.motion.flash-nvim" },
  -- { import = "astrocommunity.motion.flit-nvim" },
  -- { import = "astrocommunity.motion.grapple-nvim" },
  -- { import = "astrocommunity.motion.harp-nvim" },
  -- { import = "astrocommunity.motion.harpoon" },
  -- { import = "astrocommunity.motion.hop-nvim" },
  -- { import = "astrocommunity.motion.leap-nvim" },
  -- { import = "astrocommunity.motion.marks-nvim" },
  -- { import = "astrocommunity.motion.mini-ai" },
  -- { import = "astrocommunity.motion.mini-basics" },
  -- { import = "astrocommunity.motion.mini-bracketed" },
  -- { import = "astrocommunity.motion.mini-jump" },
  -- { import = "astrocommunity.motion.mini-move" },
  -- { import = "astrocommunity.motion.mini-surround" },
  -- { import = "astrocommunity.motion.nvim-spider" },
  -- { import = "astrocommunity.motion.nvim-surround" },
  -- { import = "astrocommunity.motion.nvim-tree-pairs" },
  -- { import = "astrocommunity.motion.portal-nvim" },
  -- { import = "astrocommunity.motion.tabout-nvim" },
  -- { import = "astrocommunity.motion.vim-matchup" },

  -- { import = "astrocommunity.neovim-lua-development.helpview-nvim" },
  -- { import = "astrocommunity.neovim-lua-development.lazydev-nvim" },
  -- { import = "astrocommunity.neovim-lua-development.lua-console-nvim" },

  -- { import = "astrocommunity.note-taking.global-note-nvim" },
  -- { import = "astrocommunity.note-taking.neorg" },
  -- { import = "astrocommunity.note-taking.obsidian-nvim" },
  -- { import = "astrocommunity.note-taking.venn-nvim" },
  -- { import = "astrocommunity.note-taking.zk-nvim" },

  -- { import = "astrocommunity.pack.angular" },
  -- { import = "astrocommunity.pack.ansible" },
  -- { import = "astrocommunity.pack.astro" },
  -- { import = "astrocommunity.pack.bash" },
  -- { import = "astrocommunity.pack.blade" },
  -- { import = "astrocommunity.pack.chezmoi" },
  -- { import = "astrocommunity.pack.clojure" },
  -- { import = "astrocommunity.pack.cmake" },
  -- { import = "astrocommunity.pack.cpp" },
  -- { import = "astrocommunity.pack.crystal" },
  -- { import = "astrocommunity.pack.cs" },
  -- { import = "astrocommunity.pack.cs-omnisharp" },
  -- { import = "astrocommunity.pack.cue" },
  -- { import = "astrocommunity.pack.dart" },
  -- { import = "astrocommunity.pack.docker" },
  -- { import = "astrocommunity.pack.edgedb" },
  -- { import = "astrocommunity.pack.elixir-phoenix" },
  -- { import = "astrocommunity.pack.elm" },
  -- { import = "astrocommunity.pack.fish" },
  -- { import = "astrocommunity.pack.full-dadbod" },
  -- { import = "astrocommunity.pack.gleam" },
  -- { import = "astrocommunity.pack.go" },
  -- { import = "astrocommunity.pack.godot" },
  -- { import = "astrocommunity.pack.golangci-lint" },
  -- { import = "astrocommunity.pack.harper" },
  -- { import = "astrocommunity.pack.haskell" },
  -- { import = "astrocommunity.pack.haxe" },
  -- { import = "astrocommunity.pack.helm" },
  -- { import = "astrocommunity.pack.html-css" },
  -- { import = "astrocommunity.pack.hyprlang" },
  -- { import = "astrocommunity.pack.java" },
  -- { import = "astrocommunity.pack.jj" },
  -- { import = "astrocommunity.pack.json" },
  -- { import = "astrocommunity.pack.julia" },
  -- { import = "astrocommunity.pack.just" },
  -- { import = "astrocommunity.pack.kotlin" },
  -- { import = "astrocommunity.pack.laravel" },
  -- { import = "astrocommunity.pack.lean" },
  { import = "astrocommunity.pack.lua" },
  -- { import = "astrocommunity.pack.markdown" },
  -- { import = "astrocommunity.pack.mdx" },
  -- { import = "astrocommunity.pack.moonbit" },
  -- { import = "astrocommunity.pack.nextflow" },
  -- { import = "astrocommunity.pack.nim" },
  -- { import = "astrocommunity.pack.nix" },
  -- { import = "astrocommunity.pack.nvchad-ui" },
  -- { import = "astrocommunity.pack.ocaml" },
  -- { import = "astrocommunity.pack.php" },
  -- { import = "astrocommunity.pack.pkl" },
  -- { import = "astrocommunity.pack.prisma" },
  -- { import = "astrocommunity.pack.proto" },
  -- { import = "astrocommunity.pack.ps1" },
  -- { import = "astrocommunity.pack.purescript" },
  -- { import = "astrocommunity.pack.python" },
  -- { import = "astrocommunity.pack.python-ruff" },
  -- { import = "astrocommunity.pack.quarto" },
  -- { import = "astrocommunity.pack.rainbow-delimiter-indent-blankline" },
  -- { import = "astrocommunity.pack.rego" },
  -- { import = "astrocommunity.pack.ruby" },
  -- { import = "astrocommunity.pack.rust" },
  -- { import = "astrocommunity.pack.scala" },
  -- { import = "astrocommunity.pack.sql" },
  -- { import = "astrocommunity.pack.svelte" },
  -- { import = "astrocommunity.pack.swift" },
  -- { import = "astrocommunity.pack.tailwindcss" },
  -- { import = "astrocommunity.pack.templ" },
  -- { import = "astrocommunity.pack.terraform" },
  -- { import = "astrocommunity.pack.thrift" },
  -- { import = "astrocommunity.pack.toml" },
  -- { import = "astrocommunity.pack.typescript" },
  -- { import = "astrocommunity.pack.typescript-all-in-one" },
  -- { import = "astrocommunity.pack.typescript-deno" },
  -- { import = "astrocommunity.pack.typst" },
  -- { import = "astrocommunity.pack.verilog" },
  -- { import = "astrocommunity.pack.vue" },
  -- { import = "astrocommunity.pack.wgsl" },
  -- { import = "astrocommunity.pack.xml" },
  -- { import = "astrocommunity.pack.yaml" },
  -- { import = "astrocommunity.pack.zig" },

  -- { import = "astrocommunity.programming-language-support.csv-vim" },
  -- { import = "astrocommunity.programming-language-support.dooku-nvim" },
  -- { import = "astrocommunity.programming-language-support.nvim-jqx" },
  -- { import = "astrocommunity.programming-language-support.rest-nvim" },
  -- { import = "astrocommunity.programming-language-support.web-tools-nvim" },
  -- { import = "astrocommunity.programming-language-support.xbase" },

  -- { import = "astrocommunity.project.linear-nvim" },
  -- { import = "astrocommunity.project.neoconf-nvim" },
  -- { import = "astrocommunity.project.project-nvim" },
  -- { import = "astrocommunity.project.projectmgr-nvim" },

  { import = "astrocommunity.quickfix.nvim-bqf" },
  { import = "astrocommunity.quickfix.quicker-nvim" },

  -- { import = "astrocommunity.recipes.ai" },
  -- { import = "astrocommunity.recipes.astrolsp-auto-signature-help" },
  -- { import = "astrocommunity.recipes.astrolsp-no-insert-inlay-hints" },
  -- { import = "astrocommunity.recipes.auto-session-restore" },
  -- { import = "astrocommunity.recipes.cache-colorscheme" },
  -- { import = "astrocommunity.recipes.diagnostic-virtual-lines-current-line" },
  -- { import = "astrocommunity.recipes.disable-tabline" },
  { import = "astrocommunity.recipes.heirline-clock-statusline" },
  -- { import = "astrocommunity.recipes.heirline-mode-text-statusline" },
  -- { import = "astrocommunity.recipes.heirline-nvchad-statusline" },
  -- { import = "astrocommunity.recipes.heirline-tabline-buffer-number" },
  -- { import = "astrocommunity.recipes.heirline-vscode-winbar" },
  -- { import = "astrocommunity.recipes.neo-tree-dark" },
  -- { import = "astrocommunity.recipes.neovide" },
  -- { import = "astrocommunity.recipes.picker-lsp-mappings" },
  -- { import = "astrocommunity.recipes.picker-nvchad-theme" },
  -- { import = "astrocommunity.recipes.telescope-lsp-mappings" },
  -- { import = "astrocommunity.recipes.telescope-nvchad-theme" },
  { import = "astrocommunity.recipes.telescope-nvim-snacks" },
  -- { import = "astrocommunity.recipes.vscode" },
  -- { import = "astrocommunity.recipes.vscode-icons" },

  -- { import = "astrocommunity.register.nvim-neoclip-lua" },

  -- { import = "astrocommunity.remote-development.distant-nvim" },
  -- { import = "astrocommunity.remote-development.netman-nvim" },
  -- { import = "astrocommunity.remote-development.nvim-sftp-sync" },
  -- { import = "astrocommunity.remote-development.remote-sshfs-nvim" },

  -- { import = "astrocommunity.scrolling.cinnamon-nvim" },
  -- { import = "astrocommunity.scrolling.mini-animate" },
  -- { import = "astrocommunity.scrolling.neoscroll-nvim" },
  -- { import = "astrocommunity.scrolling.nvim-scrollbar" },
  -- { import = "astrocommunity.scrolling.satellite-nvim" },
  -- { import = "astrocommunity.scrolling.vim-smoothie" },

  -- { import = "astrocommunity.search.grug-far-nvim" },
  -- { import = "astrocommunity.search.nvim-hlslens" },
  -- { import = "astrocommunity.search.nvim-spectre" },
  -- { import = "astrocommunity.search.sad-nvim" },

  { import = "astrocommunity.session.vim-workspace" },

  -- { import = "astrocommunity.snippet.mini-snippets" },
  { import = "astrocommunity.snippet.nvim-snippets" },

  -- { import = "astrocommunity.split-and-window.colorful-winsep-nvim" },
  -- { import = "astrocommunity.split-and-window.edgy-nvim" },
  { import = "astrocommunity.split-and-window.mini-map" },
  -- { import = "astrocommunity.split-and-window.minimap-vim" },
  -- { import = "astrocommunity.split-and-window.neominimap-nvim" },
  -- { import = "astrocommunity.split-and-window.windows-nvim" },

  -- { import = "astrocommunity.startup.fsplash-nvim" },
  -- { import = "astrocommunity.startup.mini-starter" },

  -- { import = "astrocommunity.syntax.hlargs-nvim" },
  -- { import = "astrocommunity.syntax.vim-cool" },
  { import = "astrocommunity.syntax.vim-easy-align" },
  -- { import = "astrocommunity.syntax.vim-sandwich" },

  { import = "astrocommunity.terminal-integration.flatten-nvim" },
  { import = "astrocommunity.terminal-integration.nvim-unception" },
  -- { import = "astrocommunity.terminal-integration.toggleterm-manager-nvim" },
  -- { import = "astrocommunity.terminal-integration.vim-tmux-navigator" },
  -- { import = "astrocommunity.terminal-integration.vim-tmux-yank" },
  { import = "astrocommunity.terminal-integration.vim-tpipeline" },

  -- { import = "astrocommunity.test.neotest" },
  -- { import = "astrocommunity.test.nvim-coverage" },
  -- { import = "astrocommunity.test.vim-test" },

  -- { import = "astrocommunity.utility.hover-nvim" },
  -- { import = "astrocommunity.utility.live-server-nvim" },
  -- { import = "astrocommunity.utility.lua-json5" },
  -- { import = "astrocommunity.utility.mason-tool-installer-nvim" },
  -- { import = "astrocommunity.utility.neodim" },
  -- { import = "astrocommunity.utility.noice-nvim" },
  -- { import = "astrocommunity.utility.nvim-toggler" },
  -- { import = "astrocommunity.utility.telescope-coc-nvim" },
  { import = "astrocommunity.utility.telescope-fzy-native-nvim" },
  { import = "astrocommunity.utility.telescope-lazy-nvim" },
  -- { import = "astrocommunity.utility.telescope-live-grep-args-nvim" },
  -- { import = "astrocommunity.utility.vim-fetch" },

  -- { import = "astrocommunity.workflow.bad-practices-nvim" },
  { import = "astrocommunity.workflow.hardtime-nvim" },
  -- { import = "astrocommunity.workflow.precognition-nvim" },
}
