# vim: set syn=systemd :
[LightDM]
logind-check-graphical=true

[Seat:*]
greeter-session=lightdm-gtk-greeter

{%- if autostart is true %}

[SeatsDefault]
pam-service=lightdm
pam-autologin-service=lightdm-autologin
autologin-user=user
autologin-user-timeout=0

{% endif -%}

{#- vim: set ft=jinja: -#}
