{{ banner }}

[colors.primary]
background = "#000000"

[window]
padding = { x = 16, y = 16 }
dynamic_padding = true

[font]
size = 10.5
normal.family = "IBM Plex Mono Light"

[selection]
save_to_clipboard = true

[general]
live_config_reload = true

{#- vim: set syn=jinja.toml : -#}
