# top file management
# ------------------------------------------------------------------------------

startup_states: sls
sls_list:
  - saltutil.sync_all

# override some defaults
# ------------------------------------------------------------------------------

hash_type: sha512
enable_gpu_grains: false

fileserver_followsymlinks: true
fileserver_ignoresymlinks: false
pillar_raise_on_missing: true

# logging
# ------------------------------------------------------------------------------

cli_summary: true
color: true
log_datefmt: '%H:%M:%S'
log_fmt_console: '%(colorlevel)s  %(asctime)s,%(msecs)03d  %(colorname)-40s  %(message)s'
log_fmt_jid: '[JID: %(jid)s]'
log_level: info
log_level_logfile: debug
state_output: terse
state_output_diff: true
state_output_pct: true
state_verbose: true
strip_color: false

# miscellaneous configurations
# ------------------------------------------------------------------------------

nodegroups:
  dom0: "dom0"
  vm: "* and not dom0"
  base_template: "L@archlinux,gentoo,fedora-*,debian-*,kicksecure-*,whonix-gateway-*,whonix-workstation-*"

# vim: ft=yaml ts=2 sw=2 sts=2 et number :
