# update default roots and includes
# ------------------------------------------------------------------------------

# as per https://docs.saltproject.io/en/latest/ref/configuration/master.html,
# convention for envs is /srv/$env/{salt,pillar} or /srv/{salt,pillar}/$env and
# can be expressed using the `__env__` placeholder for dynamic env handling

file_roots:
  base:
    - /srv/salt
  user:
    - /usr/local/srv/user/salt

pillar_roots:
  base:
    - /srv/pillar
  user:
    - /usr/local/srv/user/pillar

formula_dirs:
  - /srv/formulas
  - /usr/local/srv/user/formulas


# include user's custom configs
# ------------------------------------------------------------------------------

include:
  - /usr/local/etc/salt/minion.d/*.conf

# vim: set ft=yaml ts=2 sw=2 sts=2 et number :
