# update default roots and includes
# ------------------------------------------------------------------------------

file_roots:
  base:
    - /srv/salt
  user:
    - /srv/user/salt
    # - /usr/local/srv/user/salt

pillar_roots:
  base:
    - /srv/pillar
    - /srv/pillar/base
  user:
    - /srv/user/pillar
    # - /usr/local/srv/user/pillar

formula_dirs:
  - /srv/formulas
  - /srv/user/formulas
  # - /usr/local/srv/user/formulas

# include user's custom configs
# ------------------------------------------------------------------------------

include:
  - minion.d/*
  - /usr/local/etc/salt/minion.d/*.conf

# vim: ft=yaml ts=2 sw=2 sts=2 et number :
