# local config
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ENABLE_CORRECTION="true"
ZSH_THEME="nanotech"

# exported config
export PATH="${HOME}/bin:${HOME}/.local/bin:/usr/local/bin:${PATH}"
export ZSH="${HOME}/.oh-my-zsh"
export ZSH_TMUX_AUTOSTART=true

plugins=(git tmux direnv)

source "${ZSH}/oh-my-zsh.sh"

# the other configuration(s) are in $ZSH_CUSTOM
