# local config
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ENABLE_CORRECTION="true"
ZSH_THEME="nanotech"

# exported config
export PATH="${HOME}/bin:${HOME}/.local/bin:/usr/local/bin:${PATH}/.cargo/bin:${PATH}"
export ZSH="${HOME}/.local/share/oh-my-zsh"
export ZSH_CUSTOM="${HOME}/.config/oh-my-zsh/user.d"
export ZSH_TMUX_AUTOSTART=true

plugins=(git tmux direnv)

source "${ZSH}/oh-my-zsh.sh"

