# user configuration for salt stack minion
---

# specify top order for deterministic resolution (i hope?)
default_top: base
env_order:
  - base
  - user

# actual configs
pillar_raise_on_missing: true
fileserver_followsymlinks: true
fileserver_ignoresymlinks: false
hash_type: sha256
enable_gpu_grains: false

# logging etc
color: true
log_datefmt: '%H:%M:%S'
log_fmt_console: "%(colorlevel)s %(colorname)-12s  %(asctime)s,%(msecs)03d\t  %(message)s"
log_fmt_jid: '[JID: %(jid)s]'
log_level: info
log_level_logfile: debug
state_output: terse
state_output_diff: true
state_output_pct: true
state_verbose: true
strip_color: false

# vim: set syn=yaml ts=2 sw=2 sts=2 et number :

