---@type LazySpec
return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  ft = "salt",
  event = "VeryLazy",

  opts = {
    ensure_installed = {
      "autotools-language-server",
      "awk-language-server",
      "bash-debug-adapter",
      "bash-language-server",
      "beautysh",
      "cmake-language-server",
      "cmakelang",
      "codelldb",
      "commitlint",
      "dotenv-linter",
      "editorconfig-checker",
      "gitleaks",
      "gitlint",
      "harper-ls",
      "jinja-lsp",
      "markdownlint",
      "marksman",
      "mdformat",
      "prettydiff",
      "prettypst",
      "proselint",
      "prosemd-lsp",
      "remark-cli",
      "remark-language-server",
      "rpmlint",
      "salt-lint",
      "shellcheck",
      "shellharden",
      "shfmt",
      "systemd-language-server",
      "systemdlint",
    },
  },
}
