#!/bin/bash --
set -xeuo pipefail

test ! -f Makefile || make distclean

# generated by aclocal
rm -rf aclocal.m4 autom4te.cache

# generated by autoconf
rm -f configure configure\~

# generated/installed by automake
rm -f Makefile.in
rm -rf .m4
rm -f config.{log,status,guess} install-sh "${PACKAGE}.spec" missing Makefile

# build output
rm -rf ./*.tar.*

# git status --short --untracked-files \
#   | grep -v '^ M' \
#   | cut -f2 -d\  \
#   | cut -f1 -d\/ \
#   | sort -u \
#   | xargs rm -rf
