#!/bin/env bash
set -eo pipefail

gigs(){
  echo "scale=1; ${1} / 1024" | bc
}

readarray -t mem < <(xl info | grep memory | grep -o '[0-9]\{2,\}')

used_memory=$(( mem[0] - mem[1] ))

printf "%sG/%sG (%s)" \
  "$(gigs "${used_memory}")" \
  "$(gigs "${mem[0]}")" \
  "$(echo "scale=2; ${used_memory} / ${mem[0]} * 100" | bc | cut -f1 -d\.)%"

# vim: set ts=2 sw=2 et sts number :
